# Étape de construction
FROM node:18-alpine AS builder

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances de développement
RUN npm ci

# Copier le reste des fichiers
COPY . .

# Construire l'application
RUN npm run build

# Étape de production
FROM node:18-alpine

WORKDIR /app

# Copier les dépendances de production
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production

# Copier les fichiers construits
COPY --from=builder /app/dist ./dist

# Exposer le port
EXPOSE 3001

# Changer main.js en index.js
CMD ["node", "dist/index.js"]