import axios from 'axios';

// API base URL defined directly in the service
const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';

// Interface for centers of interests (corresponds to the interets table in PostgreSQL)
export interface Interet {
  id_interet: string;      // UUID generated by the database
  id_utilisateur: string;  // User UUID
  nom_interet: string;     // Name of the center of interest
  created_at?: string;     // Creation date
  updated_at?: string;     // Update date
}

const interetService = {
  /**
   * Gets the centers of interests for a specific user
   * @param id_utilisateur - The UUID identifier of the user
   */
  getUserInterets: async (id_utilisateur: string) => {
    return axios.get(`${API_BASE_URL}/api/interets/user/${id_utilisateur}`);
  },
  
  /**
   * Adds a new center of interest for a user
   * @param id_utilisateur - The UUID identifier of the user
   * @param nom_interet - The name of the center of interest to add
   */
  addInteret: async (id_utilisateur: string, nom_interet: string) => {
    return axios.post(`${API_BASE_URL}/api/interets`, {
      id_utilisateur,
      nom_interet
    });
  },
  
  /**
   * Removes a center of interest
   * @param id_interet - The UUID identifier of the center of interest to remove
   */
  removeInteret: async (id_interet: string) => {
    return axios.delete(`${API_BASE_URL}/api/interets/${id_interet}`);
  },
  
  /**
   * Gets suggestions of centers of interests for the user
   */
  getSuggestedInterets: async () => {
    return axios.get(`${API_BASE_URL}/api/interets/suggestions`);
  },

  /**
   * Gets the matching status for the authenticated user
   */
  getMatchingStatus: async () => {
    const token = localStorage.getItem('token');
    return axios.get(`${API_BASE_URL}/api/interets/matching-status`, {
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
  },

  /**
   * Toggles matching activation for the authenticated user
   */
  toggleMatching: async () => {
    const token = localStorage.getItem('token');
    return axios.post(`${API_BASE_URL}/api/interets/toggle-matching`, {}, {
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
  }
};

export default interetService;